package com.software.modsen.ratingmicroservice.entities.driver.car;

public enum CarBrand {
    ASTON_MARTIN, AUDI, BENTLEY, BMW, BUGATTI, CADILLAC, CHEVROLET, FERRARI, FORD, HONDA, HYUNDAI,
    JAGUAR, JEEP, KIA, LAND_ROVER, LAMBORGHINI, LEXUS, MASERATI, MAZDA, MERCEDES_BENZ, MITSUBISHI,
    NISSAN, PEUGEOT, PORSCHE, ROLLS_ROYCE, SUBARU, TESLA, TOYOTA, VOLKSWAGEN, VOLVO;
}